#lang racket
(define LetterNode%(class object%(super-new)
                     (define/public (increment-frequency)
                       (+(send this set-frequency(get-frequency add1))))
                     (define/public (print)
                       (displayln(string-append get-letter ": " get-frequency)))
                     (define/public (set-left leftIn)(set! left leftIn))
                     (define/public (set-right rightIn)(set! right rightIn))
                     (define/public (set-letter letterIn)(set! letter letterIn))
                     (define/public (set-frequency frequencyIn)(set! frequency frequencyIn))
                     (define/public (get-left)left)
                     (define/public (get-right)right)
                     (define/public (get-letter)letter)
                     (define/public (get-frequency)frequencyIn)))
